### ISSUE TITLE
Scope limited to payments, paydirect missing payouts

### ISSUE THREAD

**Issue by bregjevandongen** [TrueLayer/truelayer-php#25]
## Bug description

I try to make a payout but I always get Unauthenticated (using sandbox). I think this might be because the authtoken always has scope set to payments, paydirect and not payouts. Can you please check that payout is working?

**Comment by lighe** [comment]
Hi!

Payouts need to be enabled from the Console. If you log in, then go to "Payouts API" from the sidebar you should see an "Activate" button that will guide you through the process. Once that is done your code should start working.

If you are trying to implement only refunds, you can now do this via our [refund methods](https://github.com/TrueLayer/truelayer-php#refunds). This is enabled by default.

Hope this helps!
