### ISSUE TITLE
Sandbox - Form error

### ISSUE THREAD

**Issue by WillcoWD** [TrueLayer/truelayer-php#44]
## Bug description

When make a test payment the following screen is now showing

![image](https://github.com/TrueLayer/truelayer-php/assets/6916672/0b0ddba0-dc90-4de0-af91-5a584ca2286d)

## To Reproduce

Make a test payment

## Expected behavior

Payment should go through

## Environment

- OS: Any

## Additional context

The test payments were working until last week when we realised there is an issue. It's working on production with live cards. Looking through the docs it looks like we need to pass through https://docs.truelayer.com/docs/authorisation-flow-actions#form-action-formats form input types but I couldn't see anything in the repo for this.

**Comment by lighe** [comment]
Hi! Can you please share the code that you are using to create the payment? If you are also attempting to start the authorization flow using the library rather than relying on the HPP it would be useful if you could include that as well.

**Comment by WillcoWD** [comment]
The code is:

```
<?php

use TrueLayer\Interfaces\Webhook;

class checkout_truelayer extends controller {

    public object $client;

    public function init($connect_account_id = null) {

        $this->client = \TrueLayer\Client::configure()
            ->clientId($this->site->_config['truelayer']['client_id'])
            ->clientSecret($this->site->_config['truelayer']['client_secret'])
            ->keyId($this->site->_config['truelayer']['key_id'])
            ->pemFile($this->site->_config['truelayer']['pem_file'])
            ->useProduction(defined("IS_PROD"))
            ->create();
    }

    public function create_single_payment(object $sale) {

        if ($sale->currency == 'GBP') {
            $beneficiary = $this->client->beneficiary()->externalAccount()
                ->reference("TL-" . $sale->reference)
                ->accountHolderName('Citizen Ticket Ltd')
                ->accountIdentifier(
                    $this->client->accountIdentifier()->sortCodeAccountNumber()
                        ->sortCode('831531')
                        ->accountNumber('19151663')
                );
        } else {
            $beneficiary = $this->client->beneficiary()->externalAccount()
                ->reference("TL-" . $sale->reference)
                ->accountHolderName('Company name')
                ->accountIdentifier(
                    $this->client->accountIdentifier()->iban()->iban("IBAN")
                );
        }

        $sale_user = $sale->get_user();
        if ($sale_user->id) {
            $user = $this->client->user()
                ->name($sale_user->full_name)
                ->email($sale_user->email);
        } else {
            $user = $this->client->user()
                ->name($sale->init_guest_fullname)
                ->email($sale->init_guest_email);
        }

        $payment_method = $this->client->paymentMethod()->bankTransfer()
            ->beneficiary($beneficiary);

        try {
            $created_payment = $this->client->payment()
                ->user($user)
                ->amountInMinor($sale->total * 100)
                ->currency($sale->currency)
                ->paymentMethod($payment_method)
                ->create();

            $payment = $this->client->getPayment($created_payment->getId());
            $this->client->startPaymentAuthorization($payment, $this->site->base_url . 'do/checkout/truelayer-complete/');
        } catch (\Throwable $th) {
            $this->site->log->error("Truelayer Create Payment Error: " . print_r($th->getErrors(), true));
            return false;
        }

        return $payment;
    }

    public function get_payment($payment_id) {
        return $this->client->getPayment($payment_id);
    }

    public function add_bank(object $payment, string $truelayer_bank_id) {
        $nextAction = $payment->getAuthorizationFlowNextAction();
        if ($nextAction instanceof TrueLayer\Entities\Payment\AuthorizationFlow\Action\ProviderSelectionAction) {
            $this->client->submitPaymentProvider($payment, $truelayer_bank_id);
        }
    }

    public function get_url($payment) {

        return $payment->hostedPaymentsPage()
            ->returnUri($this->site->base_url . 'do/checkout/truelayer-complete/')
            ->primaryColour('#000000')
            ->secondaryColour('#009add')
            ->tertiaryColour('#003c57')
            ->toUrl();
    }

    public function get_status(string $payment_id) {

        $payment = $this->client->getPayment($payment_id);
        return $payment->getStatus();
    }

    public function get_banks($payment) {

        $nextAction = $payment->getAuthorizationFlowNextAction();
        $providers = [];

        if ($nextAction instanceof TrueLayer\Interfaces\Payment\AuthorizationFlow\Action\ProviderSelectionActionInterface) {
            foreach ($nextAction->getProviders() as $provider) {
                $providers[] = [
                    'id' => $provider->getId(),
                    'logo' => $provider->getLogoUri(),
                    'displayable_name' => $provider->getDisplayName(),
                ];
                $provider->getId();
                $provider->getDisplayName();
                $provider->getCountryCode();
                $provider->getLogoUri();
                $provider->getIconUri();
                $provider->getBgColor();
            }
        }

        return $providers;
    }


    public function webhook() {

        $webhook = $this->client->webhook();

        $webhook->handler(function (Webhook\PaymentEventInterface $event) {

            // handle any payment event

            $payment_id = $event->getPaymentId();
            $sale = $this->parent->get_sale_by_truelayer_simp_id($payment_id);

            $this->parent->convert_truelayer_status($sale);

        })->execute();

    }

}
```

**Comment by lighe** [comment]
Thanks 👍 

Looking at the code, I believe the issue is with manually starting the authorization flow. This is not necessary as the HPP will automatically start the flow when the user is redirected. 

So the following can be removed:
```
    $this->client->startPaymentAuthorization($payment, $this->site->base_url . 'do/checkout/truelayer-complete/');
```

Let me know if this fixes your issue!

**Comment by WillcoWD** [comment]
This generates the following error

`Call to undefined method TrueLayer\Entities\Payment\PaymentRetrieved\PaymentAuthorizationRequired::getAuthorizationFlowNextAction()`

This was working in sandbox in December and it is currently working on live in the current form.

**Comment by lighe** [comment]
Hi, this looks to be related to a new feature on the HPP and is a notice that is only shown in sandbox. I'll look into what the best fix is and will update you.

Just to double check, do you need to handle the start authorization flow and provider selection yourself? As the HPP can handle all this if you simply redirect to it after the payment creation.

**Comment by WillcoWD** [comment]
Great! 
I'm afraid so. We were migrating from V1 and a requirement was for the provider selection to stay,

**Comment by lighe** [comment]
Just for additional context, what has happened is this:
- When starting the authorisation flow, we need the client app to tell us what capabilities it has. For example in order to support some EU providers the client would need to support embedded forms. These capabilities can be specified through the options [here](https://docs.truelayer.com/reference/start-payment-authorization-flow) (such as `form`)
- These fields are optional, if they are not provided we simply assume the client does not have those capabilities and we filter out providers that require them.
- In the case of the HPP though, it has those capabilities so it expects the authorisation flow to have been configured accordingly.
- Recently we’ve enabled the new warning that you see, in Sandbox only, to highlight potential misconfigurations that could lead to issues when supporting non UK providers.

The php library does not have support yet for specifying these capabilities when starting the authorisation flow. So I am suggesting the following:
- We can release a new version of the library next week
- You will (potentially) need to apply a minimal code tweak (we haven’t finalised the syntax yet).

In the meantime, rest assured this will not impact production. Does this timeline work for you?

Thanks!

**Comment by WillcoWD** [comment]
Hi Lighe.

That is perfect, thank you!

Mark

**Comment by lighe** [comment]
Hi,

Sorry for the slight delay here. We've published a new version of the library which deprecates `startPaymentAuthorization`.

If you could replace this line:
```php
$this->client->startPaymentAuthorization($payment, $this->site->base_url . 'do/checkout/truelayer-complete/');
```

With this:
```php
$this->client->paymentAuthorizationFlow($payment)
    ->returnUri($this->site->base_url . 'do/checkout/truelayer-complete/')
    ->useHPPCapabilities()
    ->start();
```

Your issue should then be resolved.

**Comment by WillcoWD** [comment]
All fixed.
Many thanks for your help
