### ISSUE TITLE
Can support Illuminate v10 packages ？

### ISSUE THREAD

**Issue by echnio** [TrueLayer/truelayer-php#48]
## Motivations

Need to upgrade framework

## Solution

The following three packages need to be upgraded

        "illuminate/validation": "^v6.0|^v7.0|^v8.0|^v9.0",
        "illuminate/support": "^v6.0|^v7.0|^v8.0|^v9.0",
        "illuminate/encryption": "^v6.0|^v7.0|^v8.0|^v9.0",

**Comment by stefandanaita** [comment]
Hello! We're planning on dropping those dependencies in the next major release, likely to get pushed to next week now. Keep an eye on #49
