### ISSUE TITLE
Refunds - Payment not found

### ISSUE THREAD

**Issue by WillcoWD** [TrueLayer/truelayer-php#52]
## Bug description

When I'm processing a refund, it says the payment is not found, when it is.

Using the following code

```
public function refund(string $payment_id, float $amount, string $reference) {

        $payment = $this->get_payment($payment_id);

        if (!$payment) {
            throw new Exception("Cannot find payment id", 1);
        }

        try {
            $this->client->refund()
                ->payment($payment)
                ->amountInMinor($amount * 100)
                ->reference($reference)
                ->create();
        } catch (\Throwable $th) {
            throw new Exception($th->getDetail());
        }
    }
```
It finds the payment id from `get_payment` function, which is

```
public function get_payment($payment_id) {
   return $this->client->getPayment($payment_id);
}
```
and the object returned is `TrueLayer\Entities\Payment\PaymentRetrieved\PaymentExecuted` so I believe it correct.

However, I'm getting the Exception object with a message `payment_id not found.`

## To Reproduce

Use above code to execute a refund

## Expected behavior

Refund payment

## Environment

- OS: Linux
- PHP 8.0
- Truelayer 1.6

**Comment by lighe** [comment]
Hi @WillcoWD 

Only `settled` payments can be refunded. If you try and refund a payment that is in the `executed` state it will fail with a 404 which explains the error you are getting. If you wait for the payment to settle then try to refund it will work.

The API team has a ticket to improve the error message to make this more obvious!

Thanks!

**Comment by lighe** [comment]
Hi,

There is no way to change payment statuses. However the refund should work for `settled` payments (settled being a terminal state).

In your original message you said the returned payment was a `PaymentExecuted` which suggests your test payment was in the executed state (which occurs before the settled state).

**Comment by WillcoWD** [comment]
Is there any update on this? Without the payment moving into Executed, we can't access the refund method.

**Comment by lighe** [comment]
Hi,

Sorry for the delay. This is not an issue with this library. Refunds can only be created for payments that are in `settled` status. See this [doc page](https://docs.truelayer.com/docs/refund-a-payment#before-you-start) for more details.
